import type { Metadata } from 'next'
import './globals.css'
import localFont from 'next/font/local'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="bg-[#F7F7F7] h-screen">{children}</body>
    </html>
  )
}
